# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.ML_pb2 as ML__pb2


class MLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitMLTask = channel.unary_unary(
                '/ML.MLService/SubmitMLTask',
                request_serializer=ML__pb2.TaskRequest.SerializeToString,
                response_deserializer=ML__pb2.TaskResponse.FromString,
                )
        self.SubmitTest = channel.unary_unary(
                '/ML.MLService/SubmitTest',
                request_serializer=ML__pb2.TestRequest.SerializeToString,
                response_deserializer=ML__pb2.TestResponse.FromString,
                )
        self.SubmitAggTask = channel.unary_unary(
                '/ML.MLService/SubmitAggTask',
                request_serializer=ML__pb2.AggregateRequest.SerializeToString,
                response_deserializer=ML__pb2.AggregateResponse.FromString,
                )


class MLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitMLTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAggTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitMLTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMLTask,
                    request_deserializer=ML__pb2.TaskRequest.FromString,
                    response_serializer=ML__pb2.TaskResponse.SerializeToString,
            ),
            'SubmitTest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTest,
                    request_deserializer=ML__pb2.TestRequest.FromString,
                    response_serializer=ML__pb2.TestResponse.SerializeToString,
            ),
            'SubmitAggTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAggTask,
                    request_deserializer=ML__pb2.AggregateRequest.FromString,
                    response_serializer=ML__pb2.AggregateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ML.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitMLTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ML.MLService/SubmitMLTask',
            ML__pb2.TaskRequest.SerializeToString,
            ML__pb2.TaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ML.MLService/SubmitTest',
            ML__pb2.TestRequest.SerializeToString,
            ML__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitAggTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ML.MLService/SubmitAggTask',
            ML__pb2.AggregateRequest.SerializeToString,
            ML__pb2.AggregateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
