# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ML.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ML.proto\x12\x02ML\";\n\x0bTaskRequest\x12\n\n\x02\x66n\x18\x01 \x01(\t\x12\x0f\n\x07to_save\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\x05\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x19\n\x0bTestRequest\x12\n\n\x02\x66n\x18\x01 \x01(\t\".\n\x0cTestResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\x12\x0c\n\x04loss\x18\x02 \x01(\x02\"+\n\x10\x41ggregateRequest\x12\x0b\n\x03\x66ns\x18\x01 \x03(\t\x12\n\n\x02\x66n\x18\x02 \x01(\t\"\x1f\n\x11\x41ggregateResponse\x12\n\n\x02\x66n\x18\x01 \x01(\t2\xb3\x01\n\tMLService\x12\x33\n\x0cSubmitMLTask\x12\x0f.ML.TaskRequest\x1a\x10.ML.TaskResponse\"\x00\x12\x31\n\nSubmitTest\x12\x0f.ML.TestRequest\x1a\x10.ML.TestResponse\"\x00\x12>\n\rSubmitAggTask\x12\x14.ML.AggregateRequest\x1a\x15.ML.AggregateResponse\"\x00\x62\x06proto3')



_TASKREQUEST = DESCRIPTOR.message_types_by_name['TaskRequest']
_TASKRESPONSE = DESCRIPTOR.message_types_by_name['TaskResponse']
_TESTREQUEST = DESCRIPTOR.message_types_by_name['TestRequest']
_TESTRESPONSE = DESCRIPTOR.message_types_by_name['TestResponse']
_AGGREGATEREQUEST = DESCRIPTOR.message_types_by_name['AggregateRequest']
_AGGREGATERESPONSE = DESCRIPTOR.message_types_by_name['AggregateResponse']
TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestResponse = _reflection.GeneratedProtocolMessageType('TestResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESPONSE,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.TestResponse)
  })
_sym_db.RegisterMessage(TestResponse)

AggregateRequest = _reflection.GeneratedProtocolMessageType('AggregateRequest', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEREQUEST,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.AggregateRequest)
  })
_sym_db.RegisterMessage(AggregateRequest)

AggregateResponse = _reflection.GeneratedProtocolMessageType('AggregateResponse', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATERESPONSE,
  '__module__' : 'ML_pb2'
  # @@protoc_insertion_point(class_scope:ML.AggregateResponse)
  })
_sym_db.RegisterMessage(AggregateResponse)

_MLSERVICE = DESCRIPTOR.services_by_name['MLService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKREQUEST._serialized_start=16
  _TASKREQUEST._serialized_end=75
  _TASKRESPONSE._serialized_start=77
  _TASKRESPONSE._serialized_end=107
  _TESTREQUEST._serialized_start=109
  _TESTREQUEST._serialized_end=134
  _TESTRESPONSE._serialized_start=136
  _TESTRESPONSE._serialized_end=182
  _AGGREGATEREQUEST._serialized_start=184
  _AGGREGATEREQUEST._serialized_end=227
  _AGGREGATERESPONSE._serialized_start=229
  _AGGREGATERESPONSE._serialized_end=260
  _MLSERVICE._serialized_start=263
  _MLSERVICE._serialized_end=442
# @@protoc_insertion_point(module_scope)
